### ISSUE TITLE
Open custom SDK project in Visual Studio

### ISSUE THREAD

**Issue by DoCode** [Microsoft/MSBuildSdks#18]
Is it the expected behavior, that a custom SDK project cannot be opened inside VS?  
Or goes something wrong on my machine...

**Comment by jeffkl** [comment]
It will work in Visual Studio 15.6+ only.  What version of Visual Studio do you have?  What exactly is the error message you're seeing?

**Comment by DoCode** [comment]
@jeffkl 
**I use the latest VS preview**

![image](https://user-images.githubusercontent.com/1489133/38143393-943b6ce2-3440-11e8-8688-5baad9406ec5.png)

**This error occours when I reference the SDK as a Project SDK like this `<Project Sdk="My.Custom.SDK">`**

![image](https://user-images.githubusercontent.com/1489133/38143370-7f142a52-3440-11e8-8ca4-6f668bc6346a.png)

**The error log from the message above**

```
=====================
30.03.2018 17:31:24
LimitedFunctionality
System.AggregateException: Project system data flow 'DebugTargetsSubscriptionService: 81150' closed because of an exception: System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: catalog
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.GetDebuggerTargets(IPropertyPagesCatalog catalog, IImmutableDictionary`2 dynamicTargets)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.<LinkExternalInput>b__42_2(Tuple`2 bunch)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass10.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: catalog
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.GetDebuggerTargets(IPropertyPagesCatalog catalog, IImmutableDictionary`2 dynamicTargets)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.<LinkExternalInput>b__42_2(Tuple`2 bunch)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass10.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: catalog
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.GetDebuggerTargets(IPropertyPagesCatalog catalog, IImmutableDictionary`2 dynamicTargets)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.<LinkExternalInput>b__42_2(Tuple`2 bunch)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass10.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()<---
<---
 ---> System.ArgumentNullException: Value cannot be null.
Parameter name: catalog
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.GetDebuggerTargets(IPropertyPagesCatalog catalog, IImmutableDictionary`2 dynamicTargets)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.<LinkExternalInput>b__42_2(Tuple`2 bunch)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass10.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: catalog
   at Microsoft.Requires.NotNull[T](T value, String parameterName)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.GetDebuggerTargets(IPropertyPagesCatalog catalog, IImmutableDictionary`2 dynamicTargets)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.DebugTargetsSubscriptionService.<LinkExternalInput>b__42_2(Tuple`2 bunch)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.ProcessMessage(Func`2 transform, KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.TransformBlock`2.<>c__DisplayClass10.<.ctor>b__3(KeyValuePair`2 messageWithId)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1.ProcessMessagesLoopCore()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Rethrow(Exception ex)
   at Microsoft.VisualStudio.ProjectSystem.ProjectErrorReporting.<>c__DisplayClass6_0.<SubmitErrorReport>b__0()
   at Microsoft.VisualStudio.ProjectSystem.ExceptionFilter.<>c__DisplayClass2_0.<Guard>b__0()
   at GuardMethodClass.GuardMethod(Func`1 , Func`2 , Func`2 )<---

===================
```

**Visual Studio output window from solutions says**

```
test-consume-custom-sdk.csproj : error  : Project file is incomplete. Expected imports are missing.
```

**Comment by jeffkl** [comment]
That looks like some problem with the Visual Studio project system.  I have a newer internal preview installed and it seems to be working.  Do you have a non-Preview installation of Visual Studio on your machine that you can try?

**Comment by DoCode** [comment]
Hmmm. It would so nice when I also have this working internal preview ;-)

Have the exact same issue with this build:

![image](https://user-images.githubusercontent.com/1489133/38144688-3ee66fc0-3446-11e8-8829-d43092143b12.png)

**Comment by jeffkl** [comment]
If its broken in 15.6.4, there's more going on than just MSBuild SDK resolution.  

@davkean should I route this to project system?  Or do you know who would be the appropriate people to route it to?

**Comment by DoCode** [comment]
@jeffkl @davkean any news here?

**Comment by DoCode** [comment]
So, Visual Studio from yesterday 15.6.5 doesn't work.
Also, 15.7 Preview 2 doesn't work.

**Comment by jeffkl** [comment]
Can you provide some exact repro steps?  I can try to debug it if I can get it to happen.

**Comment by DoCode** [comment]
Sure, very simple.
Create a new project without any other pieces of information inside the csproj file.
Then switch from `<Project Sdk="Microsoft.NET.Sdk">` to `<Project Sdk="Microsoft.Build.NoTargets">`.
And now all latest Visual Studio's 15.6.5 and 15.7 Preview 2 cannot open the csproj anymore.

**Comment by jeffkl** [comment]
Okay that sounds like #20 which I'm working on fixing!

**Comment by DoCode** [comment]
Okay, thanks. Then we wait to adopt this one...

**Comment by jeffkl** [comment]
I've fixed the SDK but you now have to include the TargetFramework otherwise Visual Studio will attempt to upgrade it.

https://github.com/Microsoft/MSBuildSdks/releases/tag/Microsoft.Build.NoTargets.1.0.26

https://www.nuget.org/packages/Microsoft.Build.NoTargets/1.0.26
